### ISSUE TITLE
导入项目失败

### ISSUE THREAD

**Issue by deardeer7** [vitaviva/compose-tetris#1]
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2020.3.1 or newer.
![image](https://user-images.githubusercontent.com/42965045/114363920-759f0200-9bab-11eb-8a61-220b665b80f1.png)
gradle error Could not find method dependencyManagement()
Android Studio 版本：Android Studio 4.1.3
好像是 gradle 版本太高了，我试了网上的[方法](https://stackoverflow.com/questions/62678785/android-support-plugin-for-intellij-idea-or-android-studio-cannot-open-this-pr/65326403l)选的低版本的 gradle 还是有问题：gradle error Could not find method dependencyManagement()。请问可以指点一下吗？

**Comment by vitaviva** [comment]
Android Studio版本太低了，建议使用Canary版本 体验完整的Compose功能：https://developer.android.com/studio/preview

**Comment by deardeer7** [comment]
> Android Studio版本太低了，建议使用Canary版本 体验完整的Compose功能：https://developer.android.com/studio/preview

ok，我下一个再导一遍试试

**Comment by deardeer7** [comment]
换了canary版本的按着引导来就ok了
