### ISSUE TITLE
Any plan to provide a APK for us?

### ISSUE THREAD

**Issue by impvd** [vitaviva/compose-tetris#4]
I tried to build the project, but got error:

> This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version xxx

**Comment by vitaviva** [comment]
I'm using the artistic fox version. I will provide a APK that can be installed directly

**Comment by vitaviva** [comment]
Now you can download latest apk in Actions
e.g. https://github.com/vitaviva/compose-tetris/actions/runs/754696679
